### ISSUE TITLE
Error on JsonString.encodeObjectList(x);

### ISSUE THREAD

**Issue by Yoda-Man** [parsodyl/json_string#3]
```dart
class Log {
  String washOption;
  DateTime date;
  String registrationNumber;
  String mobileNumber;
  String email;

  Log({
    this.washOption,
    this.date,
    this.registrationNumber,
    this.mobileNumber,
    this.email,
  });

  Log.fromJson(Map<String, dynamic> json) {
    washOption = json['washOption'];
    date = json['date'];
    registrationNumber = json['registrationNumber'];
    mobileNumber = json['mobileNumber'];
    email = json['email'];
  }


  Map<String, dynamic> toJson() => {
        'washOption': washOption,
        'date': date,
        'registrationNumber': registrationNumber,
        'mobileNumber': mobileNumber,
        'email': email,
      };
}
List<Log> logItems = [];
Log currentLogItem = new Log();


backup() async {
  try {
    var jsonString;
    jsonString = JsonString.encodeObjectList(logItems);
    final internalSource = jsonString.source;
    print(internalSource);

  } on Exception catch (e) {
    print(e.toString());
  }
}
```

**Comment by parsodyl** [comment]
Hi @Yoda-Man,

can you explain a little bit?

**Comment by Yoda-Man** [comment]
The Function backup() fails on line jsonString = JsonString.encodeObjectList(logItems);

I am trying to save the list of Log Items as a json string.

**Comment by parsodyl** [comment]
> The Function backup() fails on line jsonString = JsonString.encodeObjectList(logItems);
> 
> I am trying to save the list of Log Items as a json string.

What do you mean by it fails? What kind of error do you get?

**Comment by parsodyl** [comment]
@Yoda-Man 

The array you're trying to encode is empty, so the resulted json string is just '[]'.
Remember to mark your Log class as Jsonable (`class Log with Jsonable { }`), then add an object to your array and try again.

**Comment by Yoda-Man** [comment]
Hi I was loading the List before I call backup() I will try mark the Log Class as Jsonable and try again

**Comment by Yoda-Man** [comment]
I am still getting the same error 

import 'package:json_string/json_string.dart';

class Car with Jsonable {
  String washOption;
  DateTime date;
  String registrationNumber;
  String mobileNumber;
  String email;

  Car({
    this.washOption,
    this.date,
    this.registrationNumber,
    this.mobileNumber,
    this.email,
  });

  Car.fromJson(Map<String, dynamic> json) {
    washOption = json['washOption'];
    date = json['date'];
    registrationNumber = json['registrationNumber'];
    mobileNumber = json['mobileNumber'];
    email = json['email'];
  }


  Map<String, dynamic> toJson() => {
        'washOption': washOption,
        'date': date,
        'registrationNumber': registrationNumber,
        'mobileNumber': mobileNumber,
        'email': email,
      };
}

List<Car> cars = [];
Car currentCar = new Car();


backup() async {
  try {
    Car currentCar = new Car();
    List<Car> cars = [];
    currentCar.date = new DateTime.now();
    currentCar.email = 'N/A';
    currentCar.mobileNumber = 'N/A';

    cars.add(currentCar);

    var jsonString = JsonString.encodeObjectList(cars);
    final internalSource = jsonString.source;
    print(internalSource);

  } on Exception catch (e) {
    print(e.toString());
  }
}

**Comment by parsodyl** [comment]
DateTime is not a JSON basic data type.

Please, use StackOverflow for those kinds of things.

Thanks.
